In [51]:
import numpy as np

In [52]:
##Create an array of 10 Zeros
ZeroArray = np.zeros((10))
ZeroArray

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
 ##Create an array of 10 ones
OneArray = np.ones(10)
OneArray

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [54]:
##Create an array of 10 fives
OneArray * 5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [55]:
##Create an array of integers from 10-50
IntArray = np.random.randint(10,50,10)
IntArray

array([13, 47, 41, 29, 22, 22, 17, 34, 13, 17])

In [56]:
##Creae an array of even intergers from 10-50
EvenIntArray = np.arange(10,51,2)
EvenIntArray

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [57]:
##Create a 3x3 matrix values randing from 0-8
ThreeArray = np.array([[0,1,2],[3,4,5],[6,7,8]])
ThreeArray

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
##Use NumPy to generate a random number between 0-1
np.random.rand(1)

array([0.08299023])

In [59]:
##Create a matrix using the following statements and display it
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [60]:
##Get the sum of all values in the mat matrix
mat.sum()

325

In [61]:
##Get the standard deviation of the values in the mat matrix
mat.std()

7.211102550927978

In [62]:
##Create a new matrix of 25 ones named mat1
mat1 = np.ones(25)
mat1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
##Return mat to its original array
mat = np.arange(1,26)
mat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [64]:
##Add Mat 1 by mat
mat1 + mat

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.])

In [65]:
##Multiply the values mat 1 by mat
mat1 * mat

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])